### ISSUE TITLE
github: the releases are made as draft

### ISSUE THREAD

**Issue by CastixGitHub** [i3-workspace-names-daemon/i3-workspace-names-daemon#18]
Well, one should also provide a changelog, check that files are in place and reach consensum?

Perhaps the curl that tries to "undraft" should be removed (or at your opinion fixed)?

**Comment by FloydOtsoko** [comment]
as for the changelog: Are you thinking of a changelog for the repo/project overall?
Iirc debian changelog needs to be provided in order for the package to build correctly. So we could maybe use this file? Since it has to be updated anyways?

For checking files and reach consensum I am not sure if I understand what you mean by that...

As for the new packaging/releases: I have not yet understood what the whole thing is actually doing, but it looks like the undrafting works?
I cannot see any hints, that the release is _still_ a draft...

**Comment by CastixGitHub** [comment]
This issue was more like a comment to [this command](https://github.com/i3-workspace-names-daemon/i3-workspace-names-daemon/blob/master/.github/release.sh#L59) that doesn't work as expected:
- A mantainer needs to open up github on a browser and press some buttons to mark the release as ok
- as long as proving a description for the release
- by consensum I mean check a specific issue is solved and the proposed fix doesn't raise concerns

did you get the request to join the github org? is that expired?

**Comment by FloydOtsoko** [comment]
Well i got the invite, but I missed it. Sorry about that. it is now expired.

Ah now I understand what you mean.

1) I am still not sure if I understand, the reasoning behind this approach. In all my tests I have not found my Github token anywhere in the logs of any worker. not even with debug mode enabled. But I am willing to look into it, if you are renewing the invite, I should be able to test appropriately. I was not able to get the new approach running on my fork

2) as for logs, basically same answer. I think there should be a way to either generate the changelog from the commit history (which is probably too spamy if we do not squash when merging) or we should be able to generate it from a file maybe?
Like add a file called changelog or something, where we parse the changes from, when creating the release.

3) imho that sounds like what pull requests are for. But I think it depends on the way we want to move forward.  Like come up with a way to go, document it somewhere and stick to it.
Since you are the creator of this repo I would leave that decision to you. As I have not been able to merge (and possibly f up) anything without a PR, I have not really put thought into it tbh

**Comment by CastixGitHub** [comment]
signup on codecov to create a token is not something contributors should ever need to do (unless they are you: willing to fix codecov integration). Yet I dislike tokenless codecov is not reliable anymore; coverage just works by it's own.

(strong emphasis on "this repo")

Let's just wait some more time/needs

**Comment by FloydOtsoko** [comment]
Are we on the same page here?

Codecov is part of the testsuite, and as you said seems to work on the main repo.

I am talking about the github release action I initially used to create the release (which this issue is related to)
According to the commit history the usage of the [github action provided by softprops](https://github.com/softprops/action-gh-release) was removed in [this commit](f253f9a25504046f172e754ddda9f4549d6d7203) because of a 'leaky token in the logs' and replaced by [a shell script](https://github.com/i3-workspace-names-daemon/i3-workspace-names-daemon/blob/b3dead37399d78430df3d767aa3f355b1927b660/.github/release.sh)

the secret which would be needed has nothing to do with codecov, but with github (api)

_edit:_ even the workflow file has still these lines at the end
```
GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# this is moved to avoid leaking the token in the logs
```

**Comment by FloydOtsoko** [comment]
and since the replacement script does not work for other repos, I am not really able to test the building workflow on my fork anymore.
So if there are no concerns against it, I would bring back softprops action to release, which should get rid of the "manually un-drafting releases" problems, while also allowing contributors to use the automated building for forked repos

**Comment by CastixGitHub** [comment]
> I am not really able to test the building workflow on my fork anymore.

oh, sorry about that, try something like
`if: "github.repository == 'i3-workspace-names-daemon/i3-workspace-names-daemon'`
Can you link me to the error?

**Comment by FloydOtsoko** [comment]
the error I experienced is totally weird, and maybe results from me not having a secret named GITHUB_TOKEN (which I can't create as secrets cannot start with GITHUB_ appearently)

See [this failed build](https://github.com/FloydOtsoko/i3-workspace-names-daemon/actions/runs/11622022500/job/32366801396) if you want more details...

**Comment by CastixGitHub** [comment]
Oh, ok, it's just you would need to split `I3WND=i3-workspace-names-daemon` into two variables and forward them from the workflow environment...
but it's not worth it, just read the coverage from the build log, it's also term-missing configured.

**Comment by FloydOtsoko** [comment]
still I am not sold on this release approach.

Can you check [this release](https://github.com/FloydOtsoko/i3-workspace-names-daemon/releases/tag/v0.15.1-testing-0.1) in my fork and tell me what you think about this? It is even generating a changelog list for the release from a repo file (needs refinement probably but its a step in the right direction). As mentioned previously, I cannot see any tokens in my logs. please point me towards them if you find some...

This approach would need a repo secret in order for the action to access the api for the releases, but since we are currently using a token too....

If you could be so kind to resend the invitation to join the github organization for this project I might even be able to setup everything myself!

I could even create a PR for it, if you prefer

**Comment by CastixGitHub** [comment]
> I cannot see any tokens in my logs

Frankly I think i was hallucinated and also skipped your hints. That happens sometimes

Anyway 99% percent of projects are using that action. I don't see any reason not to do the same. Security experts surely looked at it, it is a project i don't know and can't comment about (and I didn't ever search for any token (sorry @FloydOtsoko did i mislead you into thinking I found a golden pot?))

{+  I don't see any reason not to do the same +}

Yet I don't see why i need to replace it, to bring 99 to 100, instead of implementing trivial changes to a script that can make <s>an ipotetical switch to a different git hosting platform</s> multi-remote continuous integration easier?

**Comment by FloydOtsoko** [comment]
Alright. I am already on it, while also working on a cool way to make changelog structure for releases as easy as possible.

I will provide a PR for #24 which will also see a return to using the release action.

In order to make it work over all the forked repos, the secret api token should have the same name. maybe we will need to come up with a project related name.

But I think we can discuss this on the PR, once its in!

PS: @CastixGitHub no misleading, just a little confusion ;)
